### ISSUE TITLE
Re style index.php

### ISSUE THREAD

**Issue by Ilozuluchris** [Ilozuluchris/slack_invite#1]
Re style the html part of the [index.php](https://github.com/Ilozuluchris/slack_invite/blob/master/index.php) page.
Make the page responsive and put a beautiful background picture(preferably an svg image).

**Comment by mankutila** [comment]
I'll take this one )

**Comment by Ilozuluchris** [comment]
@mankutila Okay,have at it

**Comment by mankutila** [comment]
@Ilozuluchris Can't push, maybe add me to contributors

**Comment by Ilozuluchris** [comment]
Yeah you have to fork this repo,commit your desired changes on your forked version of this repo  and open a pull request

**Comment by Ilozuluchris** [comment]
Fixed by #2
